jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: teatimeguest/setup-texlive-action@v3.2.1
      with:
        packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
        update-all-packages: true
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-jdk-${{ matrix.java }}-maven-

          '
    - continue-on-error: true
      run: "# Clean the test classes to avoid caching issues and prepare testing environment\n\
        # without running the tests\nmvn clean install -Pqulice -DskipTests -DskipITs\
        \ -Dinvoker.skip=true\n# Find script\nSCRIPT=\"${GITHUB_WORKSPACE}/src/test/scripts/test-repetition.sh\"\
        \n# Check that script is exists\nif [ ! -f \"${SCRIPT}\" ]; then\n    echo\
        \ \"Script ${SCRIPT} not found\"\n    exit 1\nfi\n# Make script runnable\n\
        chmod +x \"${SCRIPT}\"\n# Test eo-parser\n${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-parser\n\
        # Test eo-maven-plugin\n${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-maven-plugin\n\
        # Test eo-runtime\n${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-runtime\
        \ --compilation true\n"
  report-fail:
    if: failure() && github.even.pull_request == null
    name: Create issue on failure
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: jayqi/failed-build-issue-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
name: daily
on:
  repository_dispatch:
    types: trigger-ga___daily.yml
