jobs:
  ebnf:
    env:
      CONVERT_PATH: /tmp/antlr4-to-bnf-converter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      run: 'sudo apt-get update

        sudo apt-get -y install ghostscript imagemagick texlive-extra-utils pdf2svg
        inkscape

        '
    - continue-on-error: true
      uses: teatimeguest/setup-texlive-action@v3.2.1
      with:
        packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
        update-all-packages: true
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 20
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
    - continue-on-error: true
      run: 'mkdir -p "$CONVERT_PATH"

        wget --quiet http://public.yegor256.com/convert.zip -O /tmp/convert.zip

        unzip -o -d "$CONVERT_PATH" /tmp/convert.zip

        '
    - continue-on-error: true
      run: sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
    - continue-on-error: true
      run: "mvn com.yegor256:antlr2ebnf-maven-plugin:0.0.7:generate \\\n  -pl :eo-parser\
        \ --errors --batch-mode --quiet \\\n  \"-Dantlr2ebnf.convertDir=$CONVERT_PATH\"\
        \ \\\n  \"-Dantlr2ebnf.specials=eof,eol,eop,tab,untab\" \\\n  \"-Dantlr2ebnf.margin=40\"\
        \n"
    - continue-on-error: true
      run: "convert --version\nconvert --help | grep Delegates\npdfcrop --version\n\
        set -x\nfor p in Eo Phi; do\n  cp \"eo-parser/target/ebnf/org/eolang/parser/${p}.pdf\"\
        \ .\n  pdfcrop --margins '10 10 10 10' \"${p}.pdf\" \"${p}-cropped.pdf\"\n\
        \  pdf2svg \"${p}-cropped.pdf\" \"${p}.svg\"\n  convert -verbose -density\
        \ 300 -quality 100 -colorspace RGB \"${p}.svg\" \"${p}.png\"\n  mkdir -p gh-pages/ebnf\n\
        \  cp \"${p}.png\" gh-pages/ebnf\n  cp \"${p}.svg\" gh-pages/ebnf\ndone\n"
    - continue-on-error: true
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        clean: false
        folder: gh-pages
name: ebnf
on:
  repository_dispatch:
    types: trigger-ga___ebnf.yml
