jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - continue-on-error: true
      if: ${{ false }}
      run: npm install code-review-gpt
    - continue-on-error: true
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      if: ${{ false }}
      run: npx code-review-gpt review --ci=github
name: GPT-code-review
on:
  repository_dispatch:
    types: trigger-ga___gpt-code-review.yml
permissions:
  contents: read
  pull-requests: write
