concurrency:
  cancel-in-progress: true
  group: latexmk-${{ github.ref }}
jobs:
  latexmk:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: yegor256/latexmk-action@0.11.1
      with:
        depends: paper/DEPENDS.txt
        opts: -pdf
        path: paper
name: latexmk
on:
  repository_dispatch:
    types: trigger-ga___latexmk.yml
