concurrency:
  cancel-in-progress: true
  group: markdown-lint-${{ github.ref }}
jobs:
  markdown-lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
    - continue-on-error: true
      uses: articulate/actions-markdownlint@v1
name: markdown-lint
on:
  repository_dispatch:
    types: trigger-ga___markdown-lint.yml
