concurrency:
  cancel-in-progress: true
  group: mvn-${{ github.ref }}
jobs:
  mvn:
    env:
      CONVERT_PATH: /tmp/antlr4-to-bnf-converter
    name: mvn
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
    - continue-on-error: true
      if: matrix.os == 'windows-2022'
      name: Set Cargo config (Windows)
      run: 'echo [http] >> %USERPROFILE%\.cargo\config.toml

        echo multiplexing = false >> %USERPROFILE%\.cargo\config.toml

        '
      shell: cmd
    - continue-on-error: true
      run: mvn clean install -Pqulice --errors --batch-mode
    strategy:
      matrix:
        java:
        - 11
        - 20
        os:
        - ubuntu-20.04
        - windows-2022
        - macos-12
name: mvn
on:
  repository_dispatch:
    types: trigger-ga___mvn.yml
