jobs:
  check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: tracehubpm/reports-check-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        openai_token: ${{ secrets.OPENAI_API_KEY }}
name: reports-check
on:
  repository_dispatch:
    types: trigger-ga___reports-check.yml
permissions:
  contents: read
  issues: write
