concurrency:
  cancel-in-progress: true
  group: shellcheck-${{ github.ref }}
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ludeeus/action-shellcheck@master
name: shellcheck
on:
  repository_dispatch:
    types: trigger-ga___shellcheck.yml
