concurrency:
  cancel-in-progress: true
  group: up-${{ github.ref }}
jobs:
  up:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      run: 'git fetch --tags --force && \

        latest=$(git tag --sort=creatordate | tail -1) && \

        sed -E -i "s/<version>[^<]+/<version>${latest}/g" eo-maven-plugin/README.md'
    - continue-on-error: true
      uses: peter-evans/create-pull-request@v6
      with:
        assignees: yegor256
        base: master
        branch: version-up
        commit-message: new version in README
        delete-branch: true
        title: New version in README
name: up
on:
  repository_dispatch:
    types: trigger-ga___up.yml
