concurrency:
  cancel-in-progress: true
  group: year-${{ github.ref }}
jobs:
  license:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: FantasticFiasco/action-update-license-year@v3
      with:
        commitTitle: update license year
        path: '**/LICENSE.txt

          **/*.xml

          **/*.xsl

          **/*.java

          **/*.eo

          **/*.groovy

          '
        token: ${{ secrets.GITHUB_TOKEN }}
name: year
on:
  repository_dispatch:
    types: trigger-ga___year.yml
